# Generated by Django 4.1.5 on 2023-01-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('emission_time', models.DateTimeField(null=True, verbose_name='emission time')),
                ('author', models.CharField(max_length=200)),
                ('target', models.CharField(max_length=200)),
            ],
        ),
    ]
