# Generated by Django 4.1.5 on 2023-01-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
    ]
